### ISSUE TITLE
Hash Syntax patch

### ISSUE THREAD

**Issue by vhbsouza** [michaeledgar/ruby-patches#2]
You should create a patch using your hash_syntax gem. 
It'll be awesome.

**Comment by michaeledgar** [comment]
Hrm, how do you mean? Like a patched ruby that has a switch, and it rewrites loaded files to use the appropriate syntax?

**Comment by vhbsouza** [comment]
Yes, a ruby ​​patched but instead of rewriting the ruby code, the patch will allow you to create hashes like your gem does.

**Comment by michaeledgar** [comment]
I guess I'm a bit confused. The hash_syntax gem translates between the 1.8 syntax and the 1.9 syntax for hashes - it doesn't actually add any new syntax that didn't exist before. Do you mean a patch for 1.8 that allows the `{ foo: bar }` syntax?

**Comment by vhbsouza** [comment]
Yes ;D
