### ISSUE TITLE
1.9.2 garbage collection patch

### ISSUE THREAD

**Issue by iain** [michaeledgar/ruby-patches#4]
There is also a patch for adding the same garbage collection tuning as REE has over here: https://gist.github.com/856296

I think this would make an excellent addition.

**Comment by michaeledgar** [comment]
I've been looking for some of these patches! I had trouble at first doing REE because it's a full fork, but this helps a lot.

**Comment by michaeledgar** [comment]
Thanks for your contribution, iain!
