### ISSUE TITLE
Suby Patches

### ISSUE THREAD

**Issue by trans** [michaeledgar/ruby-patches#5]
You may be interested in this:

  http://rubyforge.org/projects/suby/

I believe all these patches were made against Ruby 1.8.6. Would you like to pull them over to ruby-patches project? I think that would be great. I don't really have time to do it myself right now, but feel free to pull them over and I'm available if you have questions.

**Comment by michaeledgar** [comment]
I've merged most of them, and ported at least one of the patches to 1.9. Cool! Thanks for the heads-up!
