### ISSUE TITLE
Misleading attribution of GC patches

### ISSUE THREAD

**Issue by skaes** [michaeledgar/ruby-patches#7]
The ruby GC patches were developed by me (https://github.com/skaes).

They were originally contained in railsbench (https://github.com/skaes/railsbench).

Even the home page of REE tells you so.

The REE guys just ported them to REE (as in "made them apply against their changed code base").

The canonical source for the GC patches is currently https://github.com/skaes/rvm-patchsets

**Comment by michaeledgar** [comment]
Thanks for letting me know! I've corrected the attribution - I apologize for the mistake. I didn't realize the REE folks didn't actually make any contribution to the patch. I do believe that "funny-falcon" added some accessor methods though - is this also not the case? I pulled it from a gist of his.

**Comment by skaes** [comment]
Yes, funnyfalcon added accessors.

REE added some nice documentation of the patch features (http://www.rubyenterpriseedition.com/documentation.html#_garbage_collector_performance_tuning and http://www.rubyenterpriseedition.com/documentation.html#_garbage_collector_statistics).

**Comment by michaeledgar** [comment]
Alright - let me know if there's any other way I can help out. Sorry again for the mistake!
